repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: double-quote-string-fixer
  - repo: 'https://github.com/pre-commit/mirrors-autopep8'
    rev: v1.6.0
    hooks:
      - id: autopep8
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
